Q1) Load the dataset into a pandas dataframe and display the first 5 lines of the dataset along with the column headings. Note that the text file does not have the headers, which means you will have to add them to the dataframe.

In [1]:
import pandas as pd
dataset = pd.read_csv('data.txt',sep='\s+', 
                      names=["CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX","PTRATIO","B", "LSTAT", "MEDV"])
dataset.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

Q2) Split the dataset into training (70%) and testing set (30%).

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
#extract x (all columns minus target variable) & y (target variable)
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,13].values

#split into test/train
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

#print(x_train.shape)
#print(x_test.shape)
#print(y_train.shape)
#print(y_test.shape)

Q3) Model 1: Using scikit learn, build a Linear Regression model with all the variables.

In [3]:
#Fit Linear Regression to training set
from sklearn.linear_model import LinearRegression
lrObj =LinearRegression()
lrObj.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Q4) What are the weight parameters (including the intercept) you get for Model 1.

In [4]:
print("Intercept: " , lrObj.intercept_)
print("Weight parameters: ", lrObj.coef_)

Intercept:  35.66551747813821
Weight parameters:  [-1.09414320e-01  5.06519219e-02  2.05354474e-02  2.95836038e+00
 -2.10565736e+01  4.42384226e+00  3.79211313e-04 -1.46289616e+00
  3.38912767e-01 -1.49787984e-02 -9.95572422e-01  6.08588808e-03
 -4.17265575e-01]

Q5) Use Model 1 to make a prediction on the test set. Calculate mean squared error.

In [5]:
y_pred=lrObj.predict(x_test)

# mean squared error
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y_test, y_pred)
print('MSE = ', MSE)
print(y_pred)

MSE =  25.657479113105264
[ 8.39842988 11.85571149 26.32604199 26.0983867  34.68084995 24.05699114
 16.94410037 15.29556632 22.90018915 27.89509069 30.64688983 22.92928325
 17.66708343 33.75569697 21.88627825  7.6781003  25.26112826 10.31537427
 17.84964616 16.24491623 23.67309627 20.91650336 36.35494598 15.1550867
 20.00372679 29.21802969 16.07990479 21.90418953 27.08991566 33.69605756
 19.77651858 22.15214443 22.60537952 13.5226389  33.46567921 12.61398504
 19.54165193 24.46325404 17.29983035 16.91812585 23.02835973 35.94422374
 20.87640835 17.45736434 24.15354544 20.28370434 14.46832515 20.99729697
 36.3947474  13.0223911  24.10620327 27.19181369 12.1965702  28.36713122
 21.03013772 28.36409974  9.5043192  21.79148349  7.90848511 11.80149142
 32.91324588 39.58143572 31.19364006 20.4574534  16.97305989 14.75503768
 11.79982165 23.09899611 36.43238812 21.91292852 21.8915652  20.34829776
 21.53319858 27.38068858 19.14375955 34.69079414  4.69419405 19.44380749
 20.07011105 36.02969011 17.85007603 33.10933648 14.70620902 10.57166215
 15.3470272  19.03681803 16.63127714 10.45758917 23.14606151 24.04269534
 23.71016839 35.56932658 19.53341186 19.80777946 16.8019382  30.51521546
 22.56096523 18.58835067 21.29405581 21.60471785 16.83466708 17.38404106
 17.2481498   3.35826852 24.15596327  5.76253288 20.9668623  25.62211575
 21.26223443 16.33628014 33.63544881 40.24598429 18.17033011 22.15090235
 17.41979092 28.58527921 31.23623574 30.49057206 12.10905922 39.31250629
 13.38712473  8.3607363  19.10116545 28.7565993  27.66051991 23.98196502
 33.66174116 20.20798008 24.93097281 27.97756022 33.50743167 23.88559651
 21.56615819 19.10527674 16.43943803 11.08200006 14.069915   16.63829279
 29.60490479 15.97260358 15.3140896  18.82711488 29.87152315 16.13974922
 16.32616607 28.1704371  28.59017698 13.22230439 22.90517348 20.58697629
 33.81260662 20.00756088]

Q6) Model 2: Build a linear regression model with all the variables using Normal Equations method.

In [6]:
#extract x (all columns minus target variable) & y (target variable)
x1 = dataset.iloc[:,:-1].values
y2 = dataset.iloc[:,13:].values
#add column of ones to x1 for intercept
x2 = np.append(arr=np.ones((506,1)).astype(int), values=x1, axis=1)

#split into test/train
x2_train,x2_test,y2_train,y2_test = train_test_split(x2,y2,test_size=0.3)

#Use normal equation method
#w = (xtx)i * xty
transpose=x2_train.T
mult1=np.dot(transpose, x2_train)
inverse=np.linalg.inv(mult1)
mult2=np.dot(inverse,transpose)
normal_eq = np.dot(mult2, y2_train)
print(normal_eq.shape)

(14, 1)

Q7) What are the weight parameters you get for Model 2.

In [7]:
print(normal_eq)

[[ 4.82896484e+01]
 [-8.56716320e-02]
 [ 5.28051528e-02]
 [-2.60668463e-02]
 [ 2.40548250e+00]
 [-2.08047933e+01]
 [ 2.85413346e+00]
 [ 1.31428933e-02]
 [-1.66770082e+00]
 [ 3.75301440e-01]
 [-1.71998484e-02]
 [-9.85322504e-01]
 [ 6.21131973e-03]
 [-5.88368585e-01]]

Q8) Use Model 2 to make a prediction on the test set. Calculate mean squared error.

In [8]:
#prediction
y_pred2= x2_test.dot(normal_eq)

# mean squared error
MSE2 = mean_squared_error(y2_test, y_pred2)
print('MSE = ', MSE2)
print(y_pred2)

MSE =  21.075578062647484
[[24.39003121]
 [16.03755595]
 [24.54970912]
 [27.68605227]
 [12.93262596]
 [27.45510463]
 [31.08023516]
 [34.02908603]
 [11.25478698]
 [35.38180367]
 [17.82453428]
 [23.38933472]
 [17.10684289]
 [33.48193786]
 [ 6.78432422]
 [36.11554693]
 [19.72492522]
 [12.3118389 ]
 [37.13264497]
 [20.56864633]
 [16.59023226]
 [22.74619953]
 [13.00876603]
 [40.29037074]
 [32.28975142]
 [25.56262995]
 [16.68492251]
 [18.63377159]
 [33.47015495]
 [11.36998648]
 [21.74902158]
 [22.82499336]
 [31.03629469]
 [29.91320845]
 [16.26729141]
 [36.45646274]
 [12.74566957]
 [ 7.65566583]
 [13.56632274]
 [17.28814374]
 [36.08056887]
 [26.36440494]
 [19.57502246]
 [25.17197445]
 [21.84592524]
 [22.81719748]
 [15.06679292]
 [32.05107234]
 [27.58272899]
 [29.91874583]
 [ 9.9268091 ]
 [21.61559729]
 [18.68416152]
 [33.07062078]
 [17.30163704]
 [17.44515196]
 [18.66843355]
 [32.00613724]
 [25.78033318]
 [40.82613048]
 [29.2681518 ]
 [ 5.98335933]
 [18.56141654]
 [15.44979965]
 [13.44587811]
 [27.64306238]
 [16.44118542]
 [27.49912911]
 [20.89195966]
 [19.49354785]
 [24.69764976]
 [19.20657609]
 [26.32330942]
 [16.54525659]
 [19.55450034]
 [34.17829699]
 [11.68059447]
 [21.00907322]
 [25.17647264]
 [11.28718353]
 [22.86886447]
 [40.54426526]
 [14.86459525]
 [14.18992717]
 [32.69533731]
 [26.92956891]
 [26.17460024]
 [14.38590253]
 [20.20533286]
 [20.42164402]
 [13.45634116]
 [18.86977965]
 [30.21028728]
 [20.36053242]
 [34.1220873 ]
 [28.54974138]
 [20.90309354]
 [13.725446  ]
 [12.92712203]
 [27.88532287]
 [12.5335821 ]
 [ 3.15156719]
 [15.11917134]
 [22.17531756]
 [20.92794502]
 [31.42921548]
 [18.47443338]
 [23.73014587]
 [14.660102  ]
 [14.95629194]
 [20.18737671]
 [13.13089157]
 [36.44054596]
 [32.59747768]
 [22.75142031]
 [20.95529969]
 [15.65794756]
 [33.79789143]
 [24.42429652]
 [13.65623551]
 [28.70205435]
 [18.85676033]
 [15.8593316 ]
 [19.4799953 ]
 [16.10934494]
 [35.17026011]
 [34.43766498]
 [19.26159498]
 [26.47867077]
 [ 9.48587197]
 [14.95084027]
 [18.6357574 ]
 [ 4.36938477]
 [ 7.85565922]
 [12.72576369]
 [37.47260693]
 [24.30040484]
 [20.07794413]
 [34.76439057]
 [22.96514124]
 [ 8.84139836]
 [19.07052977]
 [25.37387832]
 [20.05014003]
 [11.83349599]
 [15.86200199]
 [25.26649075]
 [19.90573005]
 [18.64324171]
 [34.74935175]
 [14.71320571]
 [32.47887701]]

In [9]:
print(y2_test)

[[22.2]
 [15.6]
 [23.1]
 [25.2]
 [ 9.5]
 [23.7]
 [35.4]
 [28.2]
 [15.6]
 [33.2]
 [12.7]
 [24.7]
 [17.6]
 [26.7]
 [10.5]
 [30.1]
 [19.9]
 [10.5]
 [36. ]
 [20.4]
 [19.1]
 [22.5]
 [15.6]
 [50. ]
 [27.5]
 [23.9]
 [19.1]
 [14.1]
 [31.7]
 [ 5.6]
 [20.7]
 [20.6]
 [28.7]
 [22.8]
 [17.1]
 [36.5]
 [12.3]
 [ 8.5]
 [13.4]
 [19.9]
 [50. ]
 [23.2]
 [18.4]
 [21.5]
 [20.1]
 [21.4]
 [14.8]
 [29.9]
 [23.9]
 [32.7]
 [15.2]
 [23.2]
 [20.6]
 [41.3]
 [10.2]
 [19.3]
 [18.7]
 [29. ]
 [22.9]
 [50. ]
 [24.4]
 [13.8]
 [20.8]
 [17.8]
 [ 8.3]
 [42.8]
 [23.1]
 [22.1]
 [19.5]
 [21.4]
 [20.5]
 [17.7]
 [19.4]
 [20.6]
 [19.9]
 [50. ]
 [11.8]
 [18.8]
 [23.9]
 [10.8]
 [19.3]
 [48.8]
 [18.9]
 [13.9]
 [32.5]
 [22.2]
 [22.8]
 [18.2]
 [15.3]
 [24.5]
 [13.4]
 [14.6]
 [24.6]
 [18.5]
 [28.5]
 [28. ]
 [20.9]
 [17.2]
 [13.3]
 [22.6]
 [12.8]
 [14.4]
 [17.4]
 [25. ]
 [18.8]
 [29. ]
 [16.6]
 [23.4]
 [16.2]
 [10.4]
 [20.5]
 [13.6]
 [33.4]
 [27.9]
 [20.3]
 [19.3]
 [13.3]
 [31.6]
 [24.6]
 [18.5]
 [23.3]
 [19.5]
 [11.7]
 [16. ]
 [18.1]
 [33.8]
 [32. ]
 [18.3]
 [24.8]
 [ 7.2]
 [13.1]
 [15. ]
 [ 8.4]
 [14.6]
 [13.4]
 [43.1]
 [20.3]
 [17.1]
 [46.7]
 [11.9]
 [13.2]
 [18.2]
 [25.3]
 [21.5]
 [12. ]
 [15.2]
 [25. ]
 [20.4]
 [19.8]
 [31. ]
 [ 9.6]
 [50. ]]